[package]
name = "libnoblit"
version = "0.0.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]

[dependencies]
noblit = { path = "../noblit" }

[lib]
# Build a C dynamic and static library.
crate-type = ["cdylib", "staticlib"]
name = "noblit"
