# Don't spam me please, I'll check Travis manually.
notifications:
  email: false

language: generic

cache:
  directories:
  - $HOME/.stack
  - $HOME/.cargo

addons:
  apt:
    packages:
      # Required for GHC.
      - libgmp-dev
      # For building documentation.
      - mkdocs

before_install:
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - travis_retry curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=1.28.0 -y
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH

install:
  - cd $TRAVIS_BUILD_DIR/client/haskell
  - stack setup

script:
  # Noblit itself.
  - cargo build
  - cargo test

  # Haskell client library.
  - cd $TRAVIS_BUILD_DIR/client/haskell
  - stack --no-terminal build
  - stack --no-terminal test

  # Documentation.
  - mkdocs build
