# Don't spam me please, I'll check Travis manually.
notifications:
  email: false

language: nix

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/client/haskell/.stack-work
  - $TRAVIS_BUILD_DIR/examples/.stack-work

before_install:
  # Bring all the tools from the pinned build environment into the PATH.
  - export PATH=$(nix-build --no-out-link)/bin:$PATH

install:
  # Trigger Rustup to download and install the Rust toolchain.
  - cargo --version

  # Set up the Haskell toolchain.
  - cd $TRAVIS_BUILD_DIR/client/haskell
  - stack setup

script:
  # Build Noblit itself, and associated binaries, and run unit tests.
  - cargo build
  - cargo test

  # Build and test the Haskell client library.
  - cd $TRAVIS_BUILD_DIR/client/haskell
  - stack --no-terminal build
  - stack --no-terminal test
  - cd $TRAVIS_BUILD_DIR

  # Build the Haskell example.
  - cd $TRAVIS_BUILD_DIR/examples
  - stack --no-terminal build
  - cd $TRAVIS_BUILD_DIR

  # Typecheck the Python code.
  - mypy --strict golden/run.py

  # Check the goldens.
  - prove --exec golden/run.py golden

  # Build the documentation. This checks for dead links etc.
  - mkdocs build
