# Don't spam me please, I'll check Travis manually.
notifications:
  email: false

language: generic

cache:
  directories:
  - $HOME/.stack
  - $HOME/.cargo

# TODO: Nix-ify this entire thing, so we can pin all the dependencies.
addons:
  apt:
    packages:
      # Required for GHC.
      - libgmp-dev
      # Package manager for typechecking Python code.
      - python3
      - python3-pip

# The test runner requires Python >= 3.6.
python: 3.6

before_install:
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - travis_retry curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=1.28.0 -y
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH

install:
  # Set up the Haskell toolchain.
  - cd $TRAVIS_BUILD_DIR/client/haskell
  - stack setup

  # Install the Python typechecker, and Mkdocs.
  - python3 -m pip install --upgrade mypy mkdocs

script:
  # Build Noblit itself, and associated binaries, and run unit tests.
  - cargo build
  - cargo test

  # Build and test the Haskell client library.
  - cd $TRAVIS_BUILD_DIR/client/haskell
  - stack --no-terminal build
  - stack --no-terminal test
  - cd $TRAVIS_BUILD_DIR

  # Build the Haskell example.
  - cd $TRAVIS_BUILD_DIR/examples
  - stack --no-terminal build
  - cd $TRAVIS_BUILD_DIR

  # Typecheck the Python code.
  - mypy --strict golden/run.py

  # Check the goldens.
  - prove --exec golden/run.py golden

  # Build the documentation. This checks for dead links etc.
  - mkdocs build
