site_name: Noblit
repo_url: https://github.com/ruuda/noblit
strict: true
theme:
  name: null
  custom_dir: theme
nav:
  - Overview: index.md
  - Concepts:
    - Data model: data-model.md
  - Examples:
    - Bug tracker: examples/bug-tracker.md
  - Internals:
    - Building: building.md
    - Golden tests: golden-tests.md
    - Files: files.md
    - Trees: htree.md
    - Query: query.md
