site_name: Noblit
repo_url: https://github.com/ruuda/noblit
strict: true
theme:
  name: null
  custom_dir: docs/theme
nav:
  - Overview: index.md
  - Concepts:
    - Data model: data-model.md
    - Query: query.md
    - Query planning: query-planning.md
  - Examples:
    - Bug tracker: examples/bug-tracker.md
  - Reference:
    - Rust API reference: reference/rust.md
    - C API reference: reference/c.md
  - Development:
    - Building: building.md
    - Golden tests: golden-tests.md
    - Fuzz tests: fuzz-tests.md
    - Resources: resources.md
  - Internals:
    - Architecture: architecture.md
    - Distributed operation: distributed-operation.md
    - Files: files.md
    - Trees: htree.md
    - Execution: execution.md
    - Query optimization: query-optimization.md
